### ISSUE TITLE
z-index 이슈

### ISSUE THREAD

**Issue by daeij0207** [honk7608/23yjms#10]
![image](https://github.com/honk7608/23yjms/assets/93827169/2f364a30-28ac-4363-81eb-deb8457aa164)

홈에 있는 저거 글씨의 값이 1이고
submenu 값이 6인데 글씨가 위에 있음

**Comment by honk7608** [comment]
Fix 됐을거야
확인하고 고쳐졌다면 직접 close 해줘!
