### ISSUE TITLE
사파리에서의 오늘의 정보 배열 이슈

### ISSUE THREAD

**Issue by daeij0207** [honk7608/23yjms#11]
https://github.com/honk7608/23yjms/assets/93827169/c4095c44-f265-4a17-bc47-8d75117bdb55

처음엔 제대로 로딩되더니 갑자기 한줄에 하나씩으로 바뀜

**Comment by honk7608** [comment]
저게 오늘의 정보 div width에 따라 칸 수가 바뀌게 만져놓은건데

하필 너가 경계에 있거나, 아님 세팅이 좀 느리거나 그런거지 버그라고 보기에는 좀... 어려움
