### ISSUE TITLE
사파리 섀도우 이슈

### ISSUE THREAD

**Issue by daeij0207** [honk7608/23yjms#3]
![image](https://user-images.githubusercontent.com/93827169/236624934-f17d406d-d0e4-4712-9963-8d49ea77c84b.jpeg)

![image](https://user-images.githubusercontent.com/93827169/236624945-b5438452-68e7-4570-b01a-5a27af51d538.jpeg)

이렇게 됨

![image](https://user-images.githubusercontent.com/93827169/236625149-cba3105d-62ed-4def-8392-836ead08cfd1.png)
PC는 ㄱㅊ

**Comment by honk7608** [comment]
Shadow 제거를 통한 픽스 커밋 완료.
확인 후 Close 바람.
