### ISSUE TITLE
게시판 번호 입력 버그

### ISSUE THREAD

**Issue by daeij0207** [honk7608/23yjms#7]
![스크린샷 2023-05-02 220112](https://user-images.githubusercontent.com/93827169/235676396-6f2ba442-8259-41b9-8dc7-03a9445e6058.png)
게시판 바로가기에서 e가 입력이 됨
여러개도 안되고 하나만
숫자랑 같이 있어도 입력이 됨
+ , - 도 하나만 입력이 됨
e+-121212 이런거 입력 가능

**Comment by daeij0207** [comment]
저거 동그라미 아니고 +임
마크다운이 되버려서

**Comment by honk7608** [comment]
e가 원래 수학적 기호로 사용되는 알파벳이라 그럼.
어차피 error뜨지는 않아서 상관 없다고 판단됨
